export const projects = [
  {
    id: "audiophile",
    about:
      "Audiophile is a full-fledged e-commerce website built specifically for audiophiles to shop for high-quality headphones, speakers and earphones with ease. Users can browse products, read product descriptions, see items in each product box, see product images, and browse similar products. Users can also manage their cart and checkout wit ease (stripe integration coming soon!)",
    techStack: [
      "react",
      "nextjs",
      "tailwind",
      "javascript",
      "react-popup",
      "react-redux",
      "redux-persist",
      "react-hot-toast",
      "react-icons",
      "git",
      "github",
    ],
    github: "https://github.com/presh-031/audiophile",
    live: "https://audiophile-navy-mu.vercel.app/",
  },
  {
    id: "gaybible",
    about:
      "Gaybible is a dedicated website created for GayBible Inc., a vibrant YouTube channel that offers the latest updates on LGBTQ culture, celebrity news, pop culture, and everything related to the LGBTQ community. The channel covers a wide range of topics, including celebrity scandals, genderqueer discussions, and global news. Stay tuned for the latest entertainment news, celebrity news, and exposed celebs.",
    techStack: [
      "react",
      "nextjs",
      "javascript",
      "swr",
      "typescript",
      "react-fast-marquee",
      "tailwind",
      "react-icons",
      "react-player",
      "react-horizontal-scrolling-menu",
      "git",
      "github",
    ],
    github: "https://github.com/presh-031/gaybible",
    live: "https://gaybible.vercel.app/",
  },
  {
    id: "designo",
    about:
      "Designo is a fictional award-winning design agency that offers a comprehensive web experience. The website showcases a meticulously crafted design system, creating a professional and visually appealing layout. Users can delight in the seamless interactions between different elements of the website. Additionally, Designo boasts a fully interactive map, enabling users to explore the various locations with ease.",
    techStack: [
      "react",
      "nextjs",
      "tailwind",
      "typescript",
      "react-leaflet",
      "javascript",
      "git",
      "github",
    ],
    github: "https://github.com/presh-031/designo",
    live: "https://designo-presh-031.vercel.app/",
  },
  {
    id: "tweeter",
    about:
      "Tweeter is an app that closely resembles the popular social media platform Twitter, which happens to be my personal favorite. This clone app allows users to effortlessly sign up or log in to their accounts. Once logged in, users can explore a timeline filled with tweets from other users. They have the ability to engage with these tweets by liking, retweeting, and bookmarking them. Users can also contribute to the platform by creating and sharing their own tweets. Tweeter also provides the option to edit profile information and delete previously published tweets, offering users greater control over their online presence.",
    techStack: [
      "react",
      "nextjs",
      "tailwind",
      "javascript",
      "react-icons",
      "typescript",
      "firebase",
      "moment",
      "react-hot-toast",
      "yup",
      "react-hookform",
      "git",
      "github",
    ],
    github: "https://github.com/presh-031/tweeter",
    live: "https://tweeter-3ee0c.web.app",
  },
];
