export const projects = [
  {
    id: "audiophile",
    about:
      "Audiophile is a full-fledged e-commerce website built specifically for audiophiles to shop for high-quality headphones, speakers and earphones with ease. Users can browse products, read product descriptions, see items in each product box, see product images, and browse similar products. Users can also manage their cart and checkout wit ease (stripe integration coming soon!)",
    techStack: [
      "react",
      "nextjs",
      "tailwind",
      "javascript",
      "react-popup",
      "react-redux",
      "redux-persist",
      "react-hot-toast",
      "react-icons",
      "git",
      "github",
    ],
    github: "https://github.com/presh-031/audiophile",
    live: "https://audiophile-navy-mu.vercel.app/",
  },
  {
    id: "gaybible",
    about: "Gaybible is a ",
    techStack: [
      "react",
      "nextjs",
      "javascript",
      "swr",
      "typescript",
      "react-fast-marquee",
      "tailwind",
      "react-icons",
      "react-player",
      "react-horizontal-scrolling-menu",
      "git",
      "github",
    ],
    github: "https://github.com/presh-031/gaybible",
    live: "https://gaybible.vercel.app/",
  },
  {
    id: "designo",
    about: "Designo is a ",
    techStack: [
      "react",
      "nextjs",
      "tailwind",
      "typescript",
      "react-leaflet",
      "javascript",
      "git",
      "github",
    ],
    github: "https://github.com/presh-031/designo",
    live: "https://designo-presh-031.vercel.app/",
  },
  {
    id: "tweeter",
    about: "Tweeter is a ",
    techStack: [
      "react",
      "nextjs",
      "tailwind",
      "javascript",
      "react-icons",
      "typescript",
      "firebase",
      "moment",
      "react-hot-toast",
      "yup",
      "react-hookform",
      "git",
      "github",
    ],
    github: "https://github.com/presh-031/tweeter",
    live: "https://tweeter-3ee0c.web.app",
  },
];
